using System.Diagnostics;
using SerilogTracing;

namespace Example;

/// <summary>
/// An activity source with no dependency on Serilog or SerilogTracing. The activities
/// generated by this source will appear in logs if a <see cref="SerilogActivityListener"/>
/// is configured. Minimum level overrides for <c>Example.ConsoleWriter</c> can be used for
/// fine-grained suppression.
/// </summary>
static class ConsoleWriter
{
    static readonly ActivitySource ActivitySource = new("Example.ConsoleWriter", "1.0.0");
    
    public static void WriteSomeInterestingInfo(int i)
    {
        using var activity = ActivitySource.StartActivity();
        Console.WriteLine($"Here's the interesting info: {i}");
    }
}
