<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="All" />
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="PublicApiGenerator" Version="11.5.4" />
        <ProjectReference Include="../../src/SerilogTracing/SerilogTracing.csproj" />
        <ProjectReference Include="..\..\src\SerilogTracing.Expressions\SerilogTracing.Expressions.csproj" />
        <ProjectReference Include="..\..\src\SerilogTracing.Instrumentation.AspNetCore\SerilogTracing.Instrumentation.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\SerilogTracing.Instrumentation.SqlClient\SerilogTracing.Instrumentation.SqlClient.csproj" />
        <ProjectReference Include="..\..\src\SerilogTracing.Sinks.Zipkin\SerilogTracing.Sinks.Zipkin.csproj" />
    </ItemGroup>

</Project>
